name: Build VoceChat App

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install
        env:
          ELECTRON_MIRROR: https://npmmirror.com/mirrors/electron/
          ELECTRON_BUILDER_BINARIES_MIRROR: https://npmmirror.com/mirrors/electron-builder-binaries/

      - name: Build
        shell: bash
        run: |
          pnpm exec tsc
          pnpm exec vite build
          pnpm exec electron-builder build --mac --x64 --publish never
        env:
          CSC_IDENTITY_AUTO_DISCOVERY: false
          ELECTRON_MIRROR: https://npmmirror.com/mirrors/electron/
          ELECTRON_BUILDER_BINARIES_MIRROR: https://npmmirror.com/mirrors/electron-builder-binaries/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: VoceChat-Mac-Intel
          path: release/**/*.dmg
